github:
  prebuilds:
    main: true
image:
  file: gitpod.Dockerfile
tasks:
  - name: install
    before: echo 'export PIP_USER=false' >> ~/.bashrc && source ~/.bashrc
    init: pip install --no-deps -r requirements.txt

gitConfig:
  alias.st: status
  alias.cm: commit
  core.autocrlf: input

vscode:
  extensions:
    - ms-python.python
    - vscodevim.vim