#unknownnerror
#github:
#  prebuilds:
#    main: true
#image:
#  file: .gitpod.Dockerfile
tasks:
  - name: install
    #before: echo 'export PIP_USER=false' >> ~/.bashrc && source ~/.bashrc
    command: pip install --no-deps -r requirements.txt

gitConfig:
  alias.st: status
  alias.cm: commit

vscode:
  extensions:
    - ms-python.python